import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'

const Title = styled.h1`
  font-size: 50px;
  color: ${({ theme }) => theme.colors.primary};
`

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Parakeet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Title>Parakeet</Title>
        <Image src="/typing.gif" width={1200} height={700} alt="Typing" />
    </>
  )
}

export default Home
